package com.teamup.project.logic;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.teamup.project.entities.UserEntity;
import com.teamup.project.enums.ErrorType;
import com.teamup.project.exceptions.ApplicationException;
import com.teamup.project.repository.SignUpDAO;
import com.teamup.project.utils.InputValidationUtils;

@Service
public class SignUpService {
	
	@Autowired
	private SignUpDAO signUpDAO;

	// ------------------------------------Creates a user-------------------------------------

	public long createUser (UserEntity user) throws ApplicationException {

		if (!InputValidationUtils.isNicknameValid(user.getNickname())) {
			throw new ApplicationException (ErrorType.WORNG_INPUT, "The nickname you inserted is invalid");
		}

		if (!InputValidationUtils.isEmailValid(user.getEmail())) {
			throw new ApplicationException (ErrorType.WORNG_INPUT, "The email you inserted is invalid");
		}

		if (!InputValidationUtils.isPasswordValid(user.getPassword())) {
			throw new ApplicationException (ErrorType.WORNG_INPUT, "The password you inserted is invalid");
		}

		if (signUpDAO.getUser(user.getEmail()) != null) {
			throw new ApplicationException (ErrorType.EMAIL_ALREADY_EXISTS, ErrorType.EMAIL_ALREADY_EXISTS.getInternalMessage());
		}

		Integer passwordHash = user.getPassword().hashCode();

		user.setPassword(passwordHash.toString());

		long autoGeneratedId = signUpDAO.createUser(user);

		return autoGeneratedId;
	}
}
