package com.teamup.project.logic;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.teamup.project.entities.ExpiredEventEntity;
import com.teamup.project.exceptions.ApplicationException;
import com.teamup.project.repository.ExpiredEventRepos;

@Controller
public class ExpiredEventController {

	@Autowired
	private ExpiredEventRepos expiredEventRepos;

	// ---------------------------------Creates a event------------------------------------

	public long createExpiredEvent (ExpiredEventEntity expiredEvent) throws ApplicationException {

		long autoGeneratedId = expiredEventRepos.createExpiredEvent(expiredEvent);

		return autoGeneratedId;
	}

	// ---------------------------------Getters------------------------------------
	
	public ExpiredEventEntity getExpiredEvent(long id) throws ApplicationException {
		
		return expiredEventRepos.getExpiredEvent(id);
	}
	
	public List<ExpiredEventEntity> getUserExpiredEvents(long userId) throws ApplicationException {
		return expiredEventRepos.getUserExpiredEvents(userId);
	}

}
